version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/code
    tty: true
    command: >
      waitress-serve --listen "*:${PORT:-8080}"
      --url-scheme=https
      --trusted-proxy '*'
      --trusted-proxy-headers 'x-forwarded-for x-forwarded-proto x-forwarded-port'
      --log-untrusted-proxy-headers
      --clear-untrusted-proxy-headers
      --threads ${WEB_CONCURRENCY:-4}
      app:app
    env_file: ./app.env
