version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/code
    tty: true
    command: >
      bash -c 'rm -f tmp/*.csv tmp/*.html tmp/*.zip &&
      pip install -r requirements.txt --no-cache-dir &&
      waitress-serve --listen "*:${PORT:-8080}"
      --url-scheme=https
      --trusted-proxy "*"
      --trusted-proxy-headers "x-forwarded-for x-forwarded-proto x-forwarded-port"
      --log-untrusted-proxy-headers
      --clear-untrusted-proxy-headers
      --threads ${WEB_CONCURRENCY:-4}
      app:app'
    env_file: ./app.env
