version: "3"

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/code
    tty: true
    command: >
      waitress-serve --listen '*:8000'
      --trusted-proxy '*'
      --trusted-proxy-headers 'x-forwarded-for x-forwarded-proto x-forwarded-port'
      --log-untrusted-proxy-headers
      --clear-untrusted-proxy-headers
      --threads 10
      app:app
    env_file: ./app.env
